### ISSUE TITLE
Add current subscription status

### ISSUE THREAD

**Issue by okainov** [okainov/munich-scripts#13]
Would be nice to have information about currently active subscription, interval and expiration date

**Comment by guipsamora** [comment]
You imagine this as the user can ask for this info, like writing /subscription and then the info showing up?

**Comment by okainov** [comment]
I would think that it should be directly displayed on the main dialog (with buro selection and "reuse last selection" button), maybe something like that.

No need to have additional command since it's an extra action for users

![image](https://user-images.githubusercontent.com/918446/67842118-d80c5b80-faf9-11e9-98ba-0e4a01617ebd.png)

**Comment by guipsamora** [comment]
I see two uses it would make sense:

1 - You have already a subscription going on and you want the status. The user would need the command /start to get this info anyway.

2 - You have a subscription and the bot messages you every 2/3 days, or at the 4th day, so that you have a reminder and a confirmation that it working. 

If you would prefer we could have a quick chat about it to decide on what to build.

**Comment by guipsamora** [comment]
@okainov What do you think about the images below?

![Screenshot 2019-12-05 at 07 58 34](https://user-images.githubusercontent.com/3289179/70211348-22a27880-1735-11ea-8c9e-3fc936fe7a3f.png)
![Screenshot 2019-12-05 at 07 58 22](https://user-images.githubusercontent.com/3289179/70211349-22a27880-1735-11ea-961e-fcd516bd28b2.png)

**Comment by okainov** [comment]
Looks perfect 👍

**Comment by guipsamora** [comment]
Thanks!! I will clean the code and do a PR then. It would be great if you could review it and give me your feedback so that I can do changes needed.
