### ISSUE TITLE
Increase the limit of subscription

### ISSUE THREAD

**Issue by guipsamora** [okainov/munich-scripts#19]
Instead of 7 days, for at least 15 days

**Comment by okainov** [comment]
The issue is that currently subscription status is getting reset for unknown reason after ~1.5 days.  I wanted to debug it deeper, but didn't have time yet.

If this is fixed, than we can rethink increasing of interval, but at the moment I think that 1 week is good enough, since probablitity to get a termin is quite high (i.e. for NE during last week I saw ~10 termins available in 3 blocks different days and grabbed one for myself)

**Comment by guipsamora** [comment]
Really?? Then you got luckier than I on this, because I subscribed for the NE Blaue Karte and seldomly I get any termin.

**Comment by okainov** [comment]
That was one of the reasons for #13 - to let people actually see the current stratus which may give some idea and answer the questions "Does thing thing do anything at all???"

**Comment by guipsamora** [comment]
What about sending a "report", every second day like: "Hey, so far we couldn't find anything, I will keep looking, your subscription will be valid until: XX.XX.XXXX"
