### ISSUE TITLE
<Verpflichtungserklärung (langfristige Aufenthalte)> is not accepted by the buro <Ausländerbehörde>

### ISSUE THREAD

**Issue by AhmedAymanSoliman** [okainov/munich-scripts#68]
Seems like appointment title <Verpflichtungserklärung (langfristige Aufenthalte)> is not accepted by the buro <Ausländerbehörde> any more

**Comment by okainov** [comment]
Thanks for the report! Looks like it's related to #67 and the problem is that ABH has changed the way they work nowadays.
I don't even see online booking option for this type of termin, please refer to https://stadt.muenchen.de/service/info/verpflichtungserklaerung-fuer-kurzaufenthalte-bis-90-tage/1063741/ for more information. In the meantime I'm going to remove ABH termins completely as fix for #67
